name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: git remote add space https://mattrybin:$HUGGING_FACE_TOKEN@huggingface.co/spaces/PeacefulParenting/demo
      - name: Push to hub
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: git push --force https://mattrybin:$HUGGING_FACE_TOKEN@huggingface.co/spaces/PeacefulParenting/demo master:main
